# IBM BlueMix - Rank and Retrieve
export RAR_JOKES_USERNAME="XXXXXXXXXXXXXXXXXXXX"
export RAR_JOKES_PASSWORD="XXXXXXXXXXXXXXXXXXX"
export RAR_JOKES_CLUSTER_ID="XXXXXXXXXXXXXXXXXXX"
export RAR_JOKES_COLLECTION_NAME="XXXXXXXXXXXXXXXXXXX"
