# IBM BlueMix - Rank and Retrieve
export RAR_WATSON_USERNAME="XXXXXXXXXXXXXXXXXXXX"
export RAR_WATSON_PASSWORD="XXXXXXXXXXXXXXXXXXX"
export RAR_WATSON_CLUSTER_ID="XXXXXXXXXXXXXXXXXXX"
export RAR_WATSON_COLLECTION_NAME="XXXXXXXXXXXXXXXXXXX"
